install.packages("SeqNet")
install.packages(BiocManager)
install.packages(shiny)
install.packages(ggplot2)
install.packages(plotly)
install.packages(igraph)
install.packages(magrittr)
install.packages(shinydashboard)
install.packages("reshape2")  
install.packages(readr)
install.packages(dplyr)
install.packages(rlang)
install.packages(readxl)
options(shiny.maxRequestSize = 1000*1024^2)
install.packages(tidyverse)
install.packages(useful)
install.packages(rsconnect)
install.packages(htmltools)
install.packages(RSQLite)
install.packages(digest) # Load the digest package
install.packages(shinyjs)
install.packages(DBI)
install.packages(RMySQL)
install.packages(DIANE)
install.packages("remotes")
