library("SeqNet")
library(BiocManager)
library(shiny)
library(ggplot2)
library(plotly)
library(igraph)
library(magrittr)
library(shinydashboard)
library("reshape2")  
library(readr)
library(dplyr)
library(rlang)
library(readxl)
options(shiny.maxRequestSize = 1000*1024^2)
library(tidyverse)
library(useful)
library(rsconnect)
library(htmltools)
library(RSQLite)
library(digest) # Load the digest package
library(shinyjs)
library(DBI)
library(RMySQL)
